export const worksheet = [
  { Código: "0001", description: "Tranca Branco", codFornecedor: 1 },
  {
    Código: "0001/1",
    description: "Cabo PP 2x0,50mm branco alma de aço",
    codFornecedor: null,
  },
  { Código: "0002", description: "Tranca Bege 2", codFornecedor: 163 },
  {
    Código: "0002/1",
    description: "Cabo 2x0mm Alma de aço",
    codFornecedor: null,
  },
  {
    Código: "0003",
    description: "Tranca Cinza Claro 3",
    codFornecedor: 211,
  },
  { Código: "0004", description: "Cinza Escuro 4", codFornecedor: 40 },
  { Código: "0005", description: "Tranca Prata 5", codFornecedor: "imp" },
  { Código: "0006", description: "Tranca Preta", codFornecedor: 6 },
  {
    Código: "0006/1",
    description: "Cabo 2x0mm Alma de aço",
    codFornecedor: null,
  },
  { Código: "0007", description: "Tranca Zebra PT/BR", codFornecedor: 7 },
  {
    Código: "0008",
    description: "Tranca Marrom Escuro 8",
    codFornecedor: 92,
  },
  {
    Código: "0008/1",
    description: "Cabo 2x0,50 alma de aço",
    codFornecedor: null,
  },
  {
    Código: "0009",
    description: "Tranca Marrom Claro",
    codFornecedor: 113,
  },
  {
    Código: "0009/1",
    description: "Cabo PP 2x0,50mm branco alma de aço",
    codFornecedor: null,
  },
  {
    Código: "0010",
    description: "Tranca Azul Tifanny",
    codFornecedor: 89,
  },
  {
    Código: "0011",
    description: "Tranca Verde mescla 11",
    codFornecedor: 212,
  },
  {
    Código: "0012",
    description: "Tranca Verde Escuto 12",
    codFornecedor: 153,
  },
  {
    Código: "0013",
    description: "Tranca Amarelo Florescente 13",
    codFornecedor: 258,
  },
  {
    Código: "0014",
    description: "Tranca Verde Florescente 14",
    codFornecedor: 161,
  },
  { Código: "0015", description: "Tranca Verde 15", codFornecedor: 28 },
  {
    Código: "0016",
    description: "Tranca Amarelo Claro 16",
    codFornecedor: 15,
  },
  {
    Código: "0017",
    description: "Tranca Amarelo 17",
    codFornecedor: 131,
  },
  {
    Código: "0018",
    description: "Tranca Amarelo Escuro",
    codFornecedor: 14,
  },
  { Código: "0019", description: "Tranca Dourado", codFornecedor: 19 },
  {
    Código: "0020",
    description: "Tranca Amarelo Escuro 18",
    codFornecedor: 14,
  },
  {
    Código: "0021",
    description: "Tranca Cor Cobre 21",
    codFornecedor: 252,
  },
  {
    Código: "0021/1",
    description: "Cabo 2x0,50 alma de aço",
    codFornecedor: null,
  },
  { Código: "0022", description: "Tranca Laranja 22", codFornecedor: 13 },
  {
    Código: "0023",
    description: "Tranca Laranja Escuro Coop Cenoura",
    codFornecedor: 116,
  },
  {
    Código: "0024",
    description: "Tranca Vermelho Resistente",
    codFornecedor: 95,
  },
  { Código: "0025", description: "Tranca Vinho", codFornecedor: 250 },
  {
    Código: "0026",
    description: "Tranca Vermelho sem Brilho",
    codFornecedor: 251,
  },
  {
    Código: "0027",
    description: "Tranca Rosa CLaro",
    codFornecedor: 261,
  },
  {
    Código: "0028",
    description: "Tranca Rosa Escuro",
    codFornecedor: 48,
  },
  {
    Código: "0029",
    description: "Tranca Rosa Claro/MangaRosa",
    codFornecedor: 137,
  },
  { Código: "0030", description: "Tranca UVA", codFornecedor: 249 },
  { Código: "0031", description: "Tranca Roxa", codFornecedor: null },
  { Código: "0032", description: "Tranca Azul BIC", codFornecedor: 6 },
  { Código: "0033", description: "Tranca Azul Piscina", codFornecedor: 98 },
  { Código: "0034", description: "Tranca Azul Medio", codFornecedor: 260 },
  {
    Código: "0035",
    description: "Tranca Marrom Madeira",
    codFornecedor: 80,
  },
  {
    Código: "0036",
    description: "Tranca Marrom Escura",
    codFornecedor: 36,
  },
  {
    Código: "0037",
    description: "Tranca Multicolor Clara",
    codFornecedor: 37,
  },
  {
    Código: "0038",
    description: "Tranca Cobre m52 New Line",
    codFornecedor: null,
  },
  {
    Código: "0039",
    description: "Tranca Vermelho Vivo 001",
    codFornecedor: null,
  },
  {
    Código: "0040",
    description: "Tranca Azul Medio 219",
    codFornecedor: null,
  },
  {
    Código: "0041",
    description: "Tranca Amarelo Dourado",
    codFornecedor: 104,
  },
  {
    Código: "0041/1",
    description: "Cabo 2x0,50 alma de aço",
    codFornecedor: null,
  },
  { Código: "0042", description: "Tranca Marfin", codFornecedor: 63 },
  {
    Código: "0043",
    description: "Cabo Tranca Salmao",
    codFornecedor: null,
  },
  {
    Código: "0044",
    description: "Cabo Tranca Grafite",
    codFornecedor: 204,
  },
  { Código: "0045", description: "Cabo Tranca Rose", codFornecedor: 101 },
  { Código: "0046", description: "Cabo Tranca mel", codFornecedor: 45 },
  {
    Código: "0047",
    description: "Cabo Tranca Amarelo Velho",
    codFornecedor: 264,
  },
  {
    Código: "0048",
    description: "Cabo PP 2x0,50mm branco alma de aço",
    codFornecedor: null,
  },
  { Código: "0049", description: "Cabo Verde Agua", codFornecedor: 122 },
  {
    Código: "0050",
    description: "Projeto Tarja Branca",
    codFornecedor: null,
  },
  {
    Código: "0051",
    description: "Tranca Rose Rayon N51/",
    codFornecedor: "60F",
  },
  {
    Código: "0054",
    description: "Tranca Vermelho Preto",
    codFornecedor: null,
  },
  {
    Código: "0055",
    description: "Tranca Verde Vermelha",
    codFornecedor: null,
  },
  {
    Código: "0057",
    description: "Tranca Vinho e Dourado",
    codFornecedor: null,
  },
  {
    Código: "0060",
    description: "Cabo 2x0,50 alma de aço",
    codFornecedor: null,
  },
  {
    Código: "0078",
    description: "Cabo pp2x0,50 MM PRETO & BRANCO",
    codFornecedor: null,
  },
  {
    Código: "0098",
    description: "Cabo PP 2x050MM AZUL TRAJA PRATA",
    codFornecedor: null,
  },
  {
    Código: "0099",
    description: "Cabo PP 2x0,50MM TRANCA PRETA RISCO BRANCO",
    codFornecedor: null,
  },
  {
    Código: "0103",
    description: "Tranca Perola Rayon N103 Bondoki L&F",
    codFornecedor: 4013,
  },
  {
    Código: "0104",
    description: "Cabo PP 2x0,50 MM TRANCA PRETA RISCO BRANCO",
    codFornecedor: null,
  },
  {
    Código: "0106",
    description: "Tranca Marrom Leve N106 WLAMAR",
    codFornecedor: 238,
  },
  {
    Código: "0107",
    description: "Tranca Cinza N107 WLAMAR",
    codFornecedor: 166,
  },
  {
    Código: "0112",
    description: "Tranca Amarelo N11 WLAMAR",
    codFornecedor: 102,
  },
  {
    Código: "0114",
    description: "Cabo PP 2x0,50MM PERA PRF",
    codFornecedor: 164,
  },
  {
    Código: "0115",
    description: "Cabo PP 2x0,50 MM Pessego PSF",
    codFornecedor: 58,
  },
  {
    Código: "0116",
    description: "Cabo PP 2x0,50MM Canela WLAMAR",
    codFornecedor: 264,
  },
  {
    Código: "0118",
    description: "Cabo PP 2x0,50 MM OLIVA 155 WLAMAR",
    codFornecedor: 155,
  },
  {
    Código: "0119",
    description: "Cabo PP 2x0,50 MM ANIS ANF WLAMAR",
    codFornecedor: 224,
  },
  {
    Código: "0120",
    description: "Cabo PP 2x0,50 MM CAJA CJF",
    codFornecedor: 111,
  },
  {
    Código: "0121",
    description: "Cabo PP 2x0,50 MM CACAU CCF 172",
    codFornecedor: 172,
  },
  {
    Código: "0122",
    description: "Cabo PP 2x0,50 MM INGA IGF",
    codFornecedor: 206,
  },
  {
    Código: "0123",
    description: "Cabo PP 2x0,50 MM AZUL OCEANO",
    codFornecedor: null,
  },
];
